defaults:
  - model/base.yaml
  - model: stylegan-v

  # Import dataset common and overwrite it with the custom one
  - dataset/base.yaml
  - dataset: talkinghead_debug

  - sampling/base.yaml
  - sampling: random

  - env/base.yaml
  - env: local
  - infra_debug.yaml
  - training/debug.yaml
